"""Refinement of the Ahrens-Beylkin grids.

Same Gauss-Newton idea as the octahedral path, with the icosahedral rotation
group in place of O_h. Each orbit contributes one weight; a generic (60-point)
orbit contributes two more parameters, carried as the position of its
representative on the sphere.

The representative is stepped in its own tangent plane and renormalised, as in
designs.py, rather than through spherical angles: the (theta, phi) chart is
singular at the poles, and the 12-point orbit sits exactly there.

Because the whole orbit is generated by the group action, the derivative of an
orbit point with respect to a tangent step of its representative is just the
group element applied to that step:  d(R p)/dp . e = R e.
"""
from mpmath import mp, mpf, fabs, lu_solve, matrix, sqrt

from .designs import _grad, conditions, exact_monomial, retract, tangent_frame
from .icosahedral import group, orbit, special_positions

SPECIAL_SIZES = (12, 20, 30)      # orbits with no free angular parameter


class ABOrbit:
    def __init__(self, rep, weight, size):
        n = sqrt(sum(v * v for v in rep))
        self.rep = [v / n for v in rep]
        self.weight = weight       # per-point weight
        self.size = size
        self.free = size not in SPECIAL_SIZES
        self.frame = tangent_frame(self.rep)

    def points(self):
        return orbit(self.rep)

    def __repr__(self):
        return f"<orbit {self.size} pts w={mp.nstr(self.weight, 10)} free={self.free}>"


def decompose(points, weights, tol=mpf("1e-9")):
    """Group a tabulated AB grid into icosahedral orbits."""
    import collections
    groups = collections.OrderedDict()
    # The rounded weight is a grouping key only. Reconstructing the weight from
    # that string would silently truncate it to the key's 12 digits, which
    # shows up as an error of ~1e-11 in the sum of weights.
    for p, w in zip(points, weights):
        groups.setdefault(mp.nstr(w, 12), []).append((p, w))
    special = special_positions()
    out = []
    for members in groups.values():
        rep, w0 = members[0]
        size = len(members)
        if size in SPECIAL_SIZES:
            # Snap onto the exact symmetry position, rotated onto the tabulated
            # one. The orbit is the same set either way; the exact
            # representative makes it exactly symmetric.
            rep = _match_special(special[size], rep)
        gen = orbit(rep, tol)
        if len(gen) != size:
            raise ValueError(
                f"orbit of {size} tabulated points generates {len(gen)}")
        out.append(ABOrbit(rep, w0, size))
    return out


def _match_special(canonical, tabulated):
    """The image of `canonical` under the group that is closest to `tabulated`."""
    best, bd = None, None
    for R in group():
        q = tuple(mp.fsum(R[i, j] * canonical[j] for j in range(3)) for i in range(3))
        d = sum((q[i] - tabulated[i]) ** 2 for i in range(3))
        if bd is None or d < bd:
            best, bd = q, d
    return best


def n_param(orbits):
    return sum(1 + (2 if o.free else 0) for o in orbits)


def image_cache(orbits):
    """Group images of each orbit representative, and of its tangent basis.

    Rebuilding this per condition dominates the cost when many single-row
    Jacobians are wanted (as in select_conditions), so it is computed once and
    passed in.
    """
    G = group()
    cache = []
    for o in orbits:
        pts = [tuple(mp.fsum(R[i, j] * o.rep[j] for j in range(3)) for i in range(3)) for R in G]
        if o.free:
            e1, e2 = o.frame
            t1 = [tuple(mp.fsum(R[i, j] * e1[j] for j in range(3)) for i in range(3)) for R in G]
            t2 = [tuple(mp.fsum(R[i, j] * e2[j] for j in range(3)) for i in range(3)) for R in G]
        else:
            t1 = t2 = None
        # the group has |G| elements but the orbit may be smaller; scale instead
        # of de-duplicating, so every image contributes 1/multiplicity
        mult = len(G) // o.size
        cache.append((pts, t1, t2, mpf(1) / mult))
    return cache


def residual_and_jacobian(orbits, conds, want_jac=True, cache=None):
    F = []
    J = matrix(len(conds), n_param(orbits)) if want_jac else None
    cache = cache if cache is not None else image_cache(orbits)

    for ci, (a, b, c) in enumerate(conds):
        total = mpf(0)
        col = 0
        for o, (pts, t1, t2, scale) in zip(orbits, cache):
            s = scale * mp.fsum(p[0] ** a * p[1] ** b * p[2] ** c for p in pts)
            total += o.weight * s
            if want_jac:
                J[ci, col] = s
                col += 1
                if o.free:
                    for t in (t1, t2):
                        d = mpf(0)
                        for p, tv in zip(pts, t):
                            g = _grad(a, b, c, p)
                            d += g[0] * tv[0] + g[1] * tv[1] + g[2] * tv[2]
                        J[ci, col] = o.weight * scale * d
                        col += 1
            else:
                col += 1 + (2 if o.free else 0)
        F.append(total - exact_monomial(a, b, c))
    return F, J


def _pack(orbits):
    x = []
    for o in orbits:
        x.append(o.weight)
        if o.free:
            x.extend([mpf(0), mpf(0)])       # tangent steps, always relative
    return x


def _apply(orbits, d):
    k = 0
    for o in orbits:
        o.weight = o.weight + d[k]; k += 1
        if o.free:
            o.rep = retract(o.rep, d[k], d[k + 1], *o.frame)
            o.frame = tangent_frame(o.rep)
            k += 2


def refine(orbits, order, target_dps, max_iter=10, verbose=False, conds=None):
    conds = conds if conds is not None else conditions(order)
    hist = []
    tol = mpf(10) ** (-target_dps)
    for it in range(max_iter):
        F, J = residual_and_jacobian(orbits, conds, cache=image_cache(orbits))
        r = max(fabs(f) for f in F)
        hist.append(r)
        if verbose:
            print(f"      iter {it}: max|residual| = {mp.nstr(r, 4)}", flush=True)
        if r < tol:
            break
        _apply(orbits, _lstsq_step(J, F))
    return hist


def materialise(orbits):
    pts, wts = [], []
    for o in orbits:
        for q in o.points():
            pts.append(q); wts.append(o.weight)
    return pts, wts


def verify(orbits, order):
    pts, wts = materialise(orbits)
    worst = mpf(0)
    for (a, b, c) in conditions(order):
        q = mp.fsum(w * p[0] ** a * p[1] ** b * p[2] ** c for p, w in zip(pts, wts))
        e = exact_monomial(a, b, c)
        denom = fabs(e) if e != 0 else mpf(1)
        worst = max(worst, fabs(q - e) / denom)
    return worst


def select_conditions(orbits, order, oversample=3, verbose=False):
    """Pick a small spanning subset of the exactness conditions.

    The full set is (order+1)^2 monomials -- 1600 at order 39 -- against a few
    dozen unknowns, because the icosahedral symmetry makes most of them
    dependent. Refining on all of them is pure cost.

    Candidates are visited stratified across degree and kept when their
    Jacobian row increases the column rank, stopping once the rank is full and
    enough extra rows have been gathered for conditioning. Rows are computed
    one at a time and the walk stops early, so the whole selection costs far
    less than one full Jacobian.

    The result is always verified against the *full* condition set afterwards,
    so a bad selection surfaces as a failed verification rather than as a
    silently wrong grid.
    """
    import collections
    n = n_param(orbits)
    by_degree = collections.OrderedDict()
    for c in conditions(order):
        by_degree.setdefault(sum(c), []).append(c)

    # round-robin across degrees: low degrees first, but never only low degrees
    candidates = []
    idx = 0
    while True:
        added = False
        for deg in sorted(by_degree):
            if idx < len(by_degree[deg]):
                candidates.append(by_degree[deg][idx])
                added = True
        if not added:
            break
        idx += 1

    cache = image_cache(orbits)
    # Cap the walk: when the Jacobian is genuinely rank-deficient the rank
    # never fills, and without a cap this visits every candidate -- 1600 of
    # them at order 39. The step solver handles a deficient Jacobian, so an
    # incomplete basis is fine; verification against the full set is what
    # actually guards correctness.
    limit = max(oversample * n, 12 * n)
    basis, chosen = [], []
    for cand in candidates[:limit]:
        _, Jrow = residual_and_jacobian(orbits, [cand], cache=cache)
        v = [Jrow[0, k] for k in range(n)]
        for u in basis:
            d = mp.fsum(v[k] * u[k] for k in range(n))
            v = [v[k] - d * u[k] for k in range(n)]
        nrm = sqrt(mp.fsum(x * x for x in v))
        if nrm > mpf("1e-14"):
            basis.append([x / nrm for x in v])
            chosen.append(cand)
        elif len(basis) >= n and len(chosen) < oversample * n:
            chosen.append(cand)          # extra rows help conditioning
        if len(basis) >= n and len(chosen) >= oversample * n:
            break

    if verbose:
        print(f"      selected {len(chosen)} of {len(conditions(order))} conditions, "
              f"rank {len(basis)}/{n}", flush=True)
    if not chosen:
        return conditions(order)
    return chosen


def _rank(J, tol=mpf("1e-18")):
    """Column rank by modified Gram-Schmidt; the matrices here are small."""
    cols = []
    for j in range(J.cols):
        v = [J[i, j] for i in range(J.rows)]
        for u in cols:
            d = mp.fsum(v[i] * u[i] for i in range(len(v)))
            v = [v[i] - d * u[i] for i in range(len(v))]
        nrm = sqrt(mp.fsum(x * x for x in v))
        if nrm > tol:
            cols.append([x / nrm for x in v])
    return len(cols)


def independent_columns(J, tol=mpf("1e-16")):
    """Indices of a maximal independent set of columns, by modified Gram-Schmidt."""
    keep, basis = [], []
    for j in range(J.cols):
        v = [J[i, j] for i in range(J.rows)]
        nrm0 = sqrt(mp.fsum(x * x for x in v))
        if nrm0 == 0:
            continue
        for u in basis:
            d = mp.fsum(v[i] * u[i] for i in range(len(v)))
            v = [v[i] - d * u[i] for i in range(len(v))]
        nrm = sqrt(mp.fsum(x * x for x in v))
        if nrm > tol * nrm0:            # relative, so column scale does not matter
            basis.append([x / nrm for x in v])
            keep.append(j)
    return keep


def _lstsq_step(J, F):
    """Gauss-Newton step, solved only in the directions the Jacobian resolves.

    The Jacobian is not always full rank -- AB-312 comes out 13 of 16 -- and
    both a normal-equations LU and mpmath's qr_solve simply refuse a singular
    matrix. Restricting to an independent set of columns and leaving the rest
    at zero gives the step the well-determined directions deserve and declines
    to move along the ones the conditions cannot see.
    """
    keep = independent_columns(J)
    m = len(keep)
    JtJ = matrix(m, m); Jtf = matrix(m, 1)
    for a in range(m):
        ja = keep[a]
        for b in range(a, m):
            jb = keep[b]
            v = mp.fsum(J[k, ja] * J[k, jb] for k in range(J.rows))
            JtJ[a, b] = v; JtJ[b, a] = v
        Jtf[a] = mp.fsum(J[k, ja] * F[k] for k in range(J.rows))
    red = lu_solve(JtJ, -Jtf)
    step = [mpf(0)] * J.cols
    for a, j in enumerate(keep):
        step[j] = red[a]
    return step


def _state(orbits):
    return [(list(o.rep), o.weight) for o in orbits]


def _restore(orbits, st):
    for o, (rep, w) in zip(orbits, st):
        o.rep = list(rep)
        o.weight = w
        o.frame = tangent_frame(o.rep)


def _sumsq(F):
    return mp.fsum(f * f for f in F)


def refine_lm(orbits, order, target_dps, conds=None, max_iter=200,
              lam0=mpf("1e-3"), verbose=False):
    """Levenberg-Marquardt: Gauss-Newton with adaptive damping.

    Plain Gauss-Newton diverges on a starting point outside the basin -- AB-552
    goes 0.4619 -> 0.03831 -> 145.9 -- because nothing constrains the step
    length. Damping the normal equations by lam * diag(J^T J) interpolates
    between the Gauss-Newton step (small lam) and a short steepest-descent step
    (large lam), and lam is adapted on whether the step actually reduced the
    residual.

    This is the cheapest form of globalisation that fits the existing
    machinery. It is not a trust-region method and makes no claim to find a
    rule that is not near the starting point.
    """
    conds = conds if conds is not None else conditions(order)
    tol = mpf(10) ** (-target_dps)
    lam = lam0
    F, J = residual_and_jacobian(orbits, conds, cache=image_cache(orbits))
    cost = _sumsq(F)
    hist = [max(fabs(f) for f in F)]
    if verbose:
        print(f"      start: max|F| = {mp.nstr(hist[0], 4)}", flush=True)

    for it in range(max_iter):
        if max(fabs(f) for f in F) < tol:
            break
        n = J.cols
        JtJ = matrix(n, n); Jtf = matrix(n, 1)
        for i in range(n):
            for j in range(i, n):
                v = mp.fsum(J[k, i] * J[k, j] for k in range(J.rows))
                JtJ[i, j] = v; JtJ[j, i] = v
            Jtf[i] = mp.fsum(J[k, i] * F[k] for k in range(J.rows))

        st = _state(orbits)
        accepted = False
        for _ in range(30):                       # inner damping search
            A = matrix(n, n)
            for i in range(n):
                for j in range(n):
                    A[i, j] = JtJ[i, j]
                A[i, i] = JtJ[i, i] * (1 + lam) + lam * mpf("1e-30")
            try:
                d = lu_solve(A, -Jtf)
            except Exception:
                lam *= 10
                continue
            _apply(orbits, [d[k] for k in range(n)])
            Fn, Jn = residual_and_jacobian(orbits, conds, cache=image_cache(orbits))
            if _sumsq(Fn) < cost:
                F, J, cost = Fn, Jn, _sumsq(Fn)
                lam = max(lam / 10, mpf("1e-25"))
                accepted = True
                break
            _restore(orbits, st)
            lam *= 10
            if lam > mpf("1e20"):
                break
        hist.append(max(fabs(f) for f in F))
        if verbose and (it < 5 or it % 20 == 0):
            print(f"      iter {it}: max|F| = {mp.nstr(hist[-1], 4)}  lam = {mp.nstr(lam, 3)}",
                  flush=True)
        if not accepted:
            break
    return hist
